DROP TRIGGER IF EXISTS TR_AUDIT_CARD_DELETE;

CREATE TRIGGER TR_AUDIT_CARD_DELETE
BEFORE DELETE ON CARD
FOR EACH ROW
BEGIN
    INSERT INTO AUDIT_CARD(
        AUDIT_TYPE,
        CARD_ID,
        DECK_ID,
        CATEGORY,
        TEXT,
        YOUTUBE,
        IMAGE
    )
    VALUES (
        'DELETE',
        OLD.ID,
        OLD.DECK_ID,
        OLD.CATEGORY,
        OLD.TEXT,
        OLD.YOUTUBE,
        OLD.IMAGE
    );
END;