CREATE
OR REPLACE EVENT EVT_CLEAN_CJ_AUDIT_TABLES ON SCHEDULE EVERY 1 DAY
DO
    BEGIN
        DELETE
        FROM AUDIT_CARD
        WHERE CREATED_ON_DATE < DATE_SUB(CURRENT_TIMESTAMP(), INTERVAL 2 WEEK);

        DELETE
        FROM AUDIT_DECK
        WHERE CREATED_ON_DATE < DATE_SUB(CURRENT_TIMESTAMP(), INTERVAL 2 WEEK);
    END;
