CREATE
OR REPLACE PROCEDURE SP_ADD_EXTRA_RESPONSE_UNDO(IN VAR_PLAYER_ID UUID)
BEGIN
    UPDATE CJ_PLAYER_STATE
    SET EXTRA_RESPONSES = EXTRA_RESPONSES - 1
    WHERE PLAYER_ID = VAR_PLAYER_ID;

    CALL SP_SPEND_CREDITS_UNDO(
            VAR_PLAYER_ID,
            (
                FN_GET_SPECIAL_COST('EXTRA-RESPONSE') +
                    FN_GET_PLAYER_HANDICAP(VAR_PLAYER_ID)
            ),
            'EXTRA-RESPONSE'
        );

    CALL SP_SET_RESPONSES_PLAYER(VAR_PLAYER_ID);
END;