DROP PROCEDURE IF EXISTS SP_ADD_EXTRA_RESPONSE;

CREATE PROCEDURE SP_ADD_EXTRA_RESPONSE(IN VAR_PLAYER_ID UUID)
BEGIN
    UPDATE PLAYER
    SET EXTRA_RESPONSES = EXTRA_RESPONSES + 1
    WHERE ID = VAR_PLAYER_ID;

    CALL SP_SPEND_CREDITS(
            VAR_PLAYER_ID,
            (
                FN_GET_SPECIAL_COST('EXTRA-RESPONSE') +
                    FN_GET_PLAYER_HANDICAP(VAR_PLAYER_ID)
            ),
            'EXTRA-RESPONSE'
        );

    CALL SP_SET_RESPONSES_PLAYER(VAR_PLAYER_ID);
END;