CREATE
OR REPLACE PROCEDURE SP_ADD_EXTRA_RESPONSE_UNDO(IN VAR_PLAYER_ID UUID)
BEGIN
    DECLARE VAR_LOBBY_ID UUID;
    DECLARE VAR_PLAYER_USER_ID UUID;

    SELECT
        LOBBY_ID,
        USER_ID
    INTO
        VAR_LOBBY_ID,
        VAR_PLAYER_USER_ID
    FROM PLAYER
    WHERE ID = VAR_PLAYER_ID;

    UPDATE PLAYER
    SET CREDITS_SPENT = CREDITS_SPENT - 2,
        EXTRA_RESPONSES = EXTRA_RESPONSES - 1
    WHERE ID = VAR_PLAYER_ID;

    DELETE
    FROM LOG_CREDITS_SPENT
    WHERE LOBBY_ID = VAR_LOBBY_ID
        AND USER_ID = VAR_PLAYER_USER_ID
        AND AMOUNT = 2
        AND CATEGORY = 'EXTRA-RESPONSE'
    ORDER BY CREATED_ON_DATE DESC
    LIMIT 1;

    CALL SP_SET_RESPONSES_PLAYER(VAR_PLAYER_ID);
END;