CREATE
OR REPLACE PROCEDURE SP_BET_ON_WIN(IN VAR_PLAYER_ID UUID, IN VAR_BET_ON_WIN INT)
BEGIN
    UPDATE CJ_PLAYER_STATE
    SET BET_ON_WIN = VAR_BET_ON_WIN
    WHERE PLAYER_ID = VAR_PLAYER_ID;

    CALL SP_SPEND_CREDITS(VAR_PLAYER_ID, VAR_BET_ON_WIN, 'BET');
END;