CREATE
OR REPLACE PROCEDURE SP_BET_ON_WIN_UNDO(IN VAR_PLAYER_ID UUID)
BEGIN
    DECLARE VAR_LOBBY_ID UUID;
    DECLARE VAR_PLAYER_USER_ID UUID;
    DECLARE VAR_BET_ON_WIN INT;

    SELECT
        LOBBY_ID,
        USER_ID,
        BET_ON_WIN
    INTO
        VAR_LOBBY_ID,
        VAR_PLAYER_USER_ID,
        VAR_BET_ON_WIN
    FROM PLAYER
    WHERE ID = VAR_PLAYER_ID;

    IF VAR_BET_ON_WIN > 0 THEN
        UPDATE PLAYER
        SET CREDITS_SPENT = CREDITS_SPENT - VAR_BET_ON_WIN,
            BET_ON_WIN = 0
        WHERE ID = VAR_PLAYER_ID;

        DELETE
        FROM LOG_CREDITS_SPENT
        WHERE LOBBY_ID = VAR_LOBBY_ID
            AND USER_ID = VAR_PLAYER_USER_ID
            AND AMOUNT = VAR_BET_ON_WIN
            AND CATEGORY = 'BET'
        ORDER BY CREATED_ON_DATE DESC
        LIMIT 1;
    END
    IF;
END;