DROP PROCEDURE IF EXISTS SP_BET_ON_WIN_UNDO;

CREATE PROCEDURE SP_BET_ON_WIN_UNDO(IN VAR_PLAYER_ID UUID)
BEGIN
    DECLARE VAR_BET_ON_WIN INT DEFAULT (
            SELECT
                BET_ON_WIN
            FROM PLAYER
            WHERE ID = VAR_PLAYER_ID
        );

    IF VAR_BET_ON_WIN > 0 THEN
        UPDATE PLAYER
        SET BET_ON_WIN = 0
        WHERE ID = VAR_PLAYER_ID;

        CALL SP_SPEND_CREDITS_UNDO(VAR_PLAYER_ID, VAR_BET_ON_WIN, 'BET');
    END
    IF;
END;