CREATE
OR REPLACE PROCEDURE SP_BLOCK_RESPONSE(
    IN VAR_PLAYER_ID UUID,
    IN VAR_TARGET_PLAYER_ID UUID
)
BEGIN
    UPDATE CJ_PLAYER_STATE
    SET EXTRA_RESPONSES = EXTRA_RESPONSES - 1
    WHERE PLAYER_ID = VAR_TARGET_PLAYER_ID;

    CALL SP_SPEND_CREDITS(
            VAR_PLAYER_ID,
            (
                FN_GET_SPECIAL_COST('BLOCK-RESPONSE') +
                    FN_GET_PLAYER_HANDICAP(VAR_PLAYER_ID)
            ),
            'BLOCK-RESPONSE'
        );

    CALL SP_BET_ON_WIN_UNDO(VAR_PLAYER_ID);
    CALL SP_BET_ON_WIN_UNDO(VAR_TARGET_PLAYER_ID);
    CALL SP_SET_RESPONSES_PLAYER(VAR_TARGET_PLAYER_ID);
END;