DROP PROCEDURE IF EXISTS SP_BET_ON_WIN;

CREATE PROCEDURE SP_BET_ON_WIN(IN VAR_PLAYER_ID CHAR(36), IN VAR_BET_ON_WIN INT)
BEGIN
    UPDATE PLAYER
    SET BET_ON_WIN = VAR_BET_ON_WIN
    WHERE ID = VAR_PLAYER_ID;

    CALL SP_SPEND_CREDITS(VAR_PLAYER_ID, VAR_BET_ON_WIN, 'BET');
END;