CREATE
OR REPLACE PROCEDURE SP_BLOCK_RESPONSE(
    IN VAR_PLAYER_ID UUID,
    IN VAR_TARGET_PLAYER_ID UUID
)
BEGIN
    UPDATE PLAYER
    SET CREDITS_SPENT = CREDITS_SPENT + 2
    WHERE ID = VAR_PLAYER_ID;

    UPDATE PLAYER
    SET EXTRA_RESPONSES = EXTRA_RESPONSES - 1
    WHERE ID = VAR_TARGET_PLAYER_ID;

    CALL SP_BET_ON_WIN_UNDO(VAR_TARGET_PLAYER_ID);

    INSERT INTO LOG_CREDITS_SPENT(LOBBY_ID, USER_ID, AMOUNT, CATEGORY)
    SELECT
        LOBBY_ID,
        USER_ID,
        2,
        'BLOCK-RESPONSE'
    FROM PLAYER
    WHERE ID = VAR_PLAYER_ID;

    CALL SP_SET_RESPONSES_PLAYER(VAR_TARGET_PLAYER_ID);
END;