CREATE
OR REPLACE PROCEDURE SP_CJ_INIT_LOBBY(IN VAR_LOBBY_ID UUID)
BEGIN
    INSERT INTO CJ_LOBBY_SETTINGS(LOBBY_ID)
    VALUES (VAR_LOBBY_ID);

    INSERT INTO JUDGE(LOBBY_ID)
    VALUES (VAR_LOBBY_ID);
END;
