CREATE
OR REPLACE PROCEDURE SP_CJ_PLAYER_INACTIVE(IN VAR_PLAYER_ID UUID)
BEGIN
    DECLARE VAR_LOBBY_ID UUID DEFAULT FN_GET_PLAYER_LOBBY_ID(VAR_PLAYER_ID);

    IF EXISTS(SELECT ID FROM JUDGE WHERE PLAYER_ID = VAR_PLAYER_ID) THEN
        -- JUDGE LEFT THE LOBBY
        CALL SP_SET_MISSING_JUDGE_PLAYER(VAR_LOBBY_ID);
        CALL SP_SET_RESPONSES_LOBBY(VAR_LOBBY_ID);
        ELSE
        -- PLAYER LEFT THE LOBBY
        CALL SP_SET_RESPONSES_PLAYER(VAR_PLAYER_ID);
    END
    IF;
END;
