CREATE
OR REPLACE PROCEDURE SP_CJ_INIT_PLAYER(IN VAR_PLAYER_ID UUID)
BEGIN
    DECLARE VAR_LOBBY_ID UUID DEFAULT FN_GET_PLAYER_LOBBY_ID(VAR_PLAYER_ID);

    INSERT INTO CJ_PLAYER_STATE(PLAYER_ID)
    VALUES (VAR_PLAYER_ID);

    CALL SP_DRAW_HAND(VAR_PLAYER_ID);
    CALL SP_SET_MISSING_JUDGE_PLAYER(VAR_LOBBY_ID);
    CALL SP_SET_MISSING_JUDGE_CARD(VAR_LOBBY_ID);
    CALL SP_SET_RESPONSES_PLAYER(VAR_PLAYER_ID);
END;
