DROP PROCEDURE IF EXISTS SP_DRAW_HAND;

CREATE PROCEDURE SP_DRAW_HAND(IN VAR_PLAYER_ID CHAR(36))
BEGIN
    DECLARE VAR_LOBBY_ID CHAR(36) DEFAULT FN_GET_PLAYER_LOBBY_ID(VAR_PLAYER_ID);
    DECLARE VAR_LOBBY_DRAW_PILE_SIZE INT;
    DECLARE VAR_FINAL_HAND_SIZE INT;
    DECLARE VAR_CURRENT_HAND_SIZE INT;
    DECLARE VAR_CARD_ID CHAR(36);

    SELECT
        COUNT(C.ID)
    INTO
        VAR_LOBBY_DRAW_PILE_SIZE
    FROM DRAW_PILE AS DP
        INNER JOIN CARD AS C ON C.ID = DP.CARD_ID
    WHERE C.CATEGORY = 'RESPONSE'
        AND DP.LOBBY_ID = VAR_LOBBY_ID;

    SET VAR_FINAL_HAND_SIZE = (
            SELECT
                HAND_SIZE
            FROM LOBBY
            WHERE ID = VAR_LOBBY_ID
        ) +
    (SELECT HAND_SIZE_ADVANTAGE FROM PLAYER WHERE ID = VAR_PLAYER_ID);

    SELECT
        COUNT(CARD_ID)
    INTO
        VAR_CURRENT_HAND_SIZE
    FROM HAND
    WHERE PLAYER_ID = VAR_PLAYER_ID;

    WHILE VAR_LOBBY_DRAW_PILE_SIZE > 0
        AND VAR_FINAL_HAND_SIZE > VAR_CURRENT_HAND_SIZE
    DO
        SET VAR_CARD_ID = FN_GET_DRAW_PILE_CARD_ID('RESPONSE', VAR_LOBBY_ID);

        INSERT INTO HAND(PLAYER_ID, CARD_ID)
        VALUES (VAR_PLAYER_ID, VAR_CARD_ID);

        DELETE
        FROM DRAW_PILE
        WHERE LOBBY_ID = VAR_LOBBY_ID
            AND CARD_ID = VAR_CARD_ID;

        SELECT
            COUNT(C.ID)
        INTO
            VAR_LOBBY_DRAW_PILE_SIZE
        FROM DRAW_PILE AS DP
            INNER JOIN CARD AS C ON C.ID = DP.CARD_ID
        WHERE C.CATEGORY = 'RESPONSE'
            AND DP.LOBBY_ID = VAR_LOBBY_ID;

        SELECT
            COUNT(CARD_ID)
        INTO
            VAR_CURRENT_HAND_SIZE
        FROM HAND
        WHERE PLAYER_ID = VAR_PLAYER_ID;
    END
    WHILE;
END;