DROP PROCEDURE IF EXISTS SP_FLIP_TABLE;

CREATE PROCEDURE SP_FLIP_TABLE(IN VAR_PLAYER_ID CHAR(36))
BEGIN
    DECLARE VAR_LOBBY_ID CHAR(36) DEFAULT FN_GET_PLAYER_LOBBY_ID(VAR_PLAYER_ID);

    DECLARE VAR_USER_ID CHAR(36) DEFAULT (
            SELECT
                USER_ID
            FROM PLAYER
            WHERE ID = VAR_PLAYER_ID
        );

    INSERT INTO LOG_FLIP_TABLE(LOBBY_ID, USER_ID)
    VALUES (VAR_LOBBY_ID, VAR_USER_ID);
END;