DROP PROCEDURE IF EXISTS SP_GAMBLE_CREDITS;

CREATE PROCEDURE SP_GAMBLE_CREDITS(IN VAR_PLAYER_ID CHAR(36), IN VAR_AMOUNT INT)
BEGIN
    DECLARE VAR_GAMBLE_WON BOOLEAN DEFAULT FALSE;
    CALL SP_SPEND_CREDITS(VAR_PLAYER_ID, VAR_AMOUNT, 'GAMBLE');

    IF RAND() > 0.55 THEN
        SET VAR_GAMBLE_WON = TRUE;

        CALL SP_SPEND_CREDITS(
                VAR_PLAYER_ID,
                (VAR_AMOUNT * 2) * -1,
                'GAMBLE-WIN'
            );
    END
    IF;

    SELECT
        VAR_GAMBLE_WON AS GAMBLE_WON;
END;