DROP PROCEDURE IF EXISTS SP_PURCHASE_CREDITS;

CREATE PROCEDURE SP_PURCHASE_CREDITS(IN VAR_PLAYER_ID UUID)
BEGIN
    DECLARE VAR_LOBBY_ID UUID DEFAULT FN_GET_PLAYER_LOBBY_ID(VAR_PLAYER_ID);
    DECLARE VAR_LOOP_DONE BOOLEAN DEFAULT FALSE;
    DECLARE VAR_OTHER_PLAYER_ID UUID;

    DECLARE VAR_PLAYER_CURSOR CURSOR
    FOR
    SELECT
        ID
    FROM PLAYER
    WHERE ID <> VAR_PLAYER_ID
        AND LOBBY_ID = VAR_LOBBY_ID;

    DECLARE CONTINUE HANDLER
    FOR NOT FOUND
    SET VAR_LOOP_DONE = TRUE;

    OPEN VAR_PLAYER_CURSOR;

        READ_LOOP: LOOP
        FETCH VAR_PLAYER_CURSOR
        INTO
            VAR_OTHER_PLAYER_ID;

        IF VAR_LOOP_DONE THEN LEAVE READ_LOOP;
        END
        IF;

        CALL SP_SPEND_CREDITS(
                VAR_OTHER_PLAYER_ID,
                (
                    FN_GET_SPECIAL_COST('PURCHASE') +
                    FN_GET_PLAYER_HANDICAP_INVERSE(VAR_OTHER_PLAYER_ID)
                ) * -1,
                'PURCHASE'
            );
        END LOOP;
    CLOSE VAR_PLAYER_CURSOR;
END;