CREATE
OR REPLACE PROCEDURE SP_PERK_HANDICAP_ADVANTAGE(IN VAR_PLAYER_ID UUID)
BEGIN
    UPDATE CJ_PLAYER_STATE
    SET HANDICAP_ADVANTAGE = 1
    WHERE PLAYER_ID = VAR_PLAYER_ID;

    CALL SP_SPEND_CREDITS(
            VAR_PLAYER_ID,
            (
                FN_GET_SPECIAL_COST('PERK') +
                    FN_GET_PLAYER_HANDICAP(VAR_PLAYER_ID)
            ),
            'PERK'
        );
END;