DROP PROCEDURE IF EXISTS SP_PERK_HAND_SIZE_ADVANTAGE;

CREATE PROCEDURE SP_PERK_HAND_SIZE_ADVANTAGE(IN VAR_PLAYER_ID CHAR(36))
BEGIN
    UPDATE PLAYER
    SET HAND_SIZE_ADVANTAGE = HAND_SIZE_ADVANTAGE + 2
    WHERE ID = VAR_PLAYER_ID;

    CALL SP_DRAW_HAND(VAR_PLAYER_ID);

    CALL SP_SPEND_CREDITS(
            VAR_PLAYER_ID,
            (
                FN_GET_SPECIAL_COST('PERK') +
                    FN_GET_PLAYER_HANDICAP(VAR_PLAYER_ID)
            ),
            'PERK'
        );
END;