DROP PROCEDURE IF EXISTS SP_RESPOND_WITH_STEAL_CARD;

CREATE PROCEDURE SP_RESPOND_WITH_STEAL_CARD(IN VAR_PLAYER_ID UUID)
BEGIN
    DECLARE VAR_LOBBY_ID UUID DEFAULT FN_GET_PLAYER_LOBBY_ID(VAR_PLAYER_ID);
    DECLARE VAR_VICTIM_PLAYER_ID UUID;
    DECLARE VAR_CARD_ID UUID;

    SELECT
        P.ID,
        C.ID
    INTO
        VAR_VICTIM_PLAYER_ID,
        VAR_CARD_ID
    FROM PLAYER AS P
        INNER JOIN HAND AS H ON H.PLAYER_ID = P.ID
        INNER JOIN CARD AS C ON C.ID = H.CARD_ID
    WHERE P.LOBBY_ID = VAR_LOBBY_ID
        AND P.ID <> VAR_PLAYER_ID
    ORDER BY RAND()
    LIMIT 1;

    DELETE
    FROM HAND
    WHERE PLAYER_ID = VAR_VICTIM_PLAYER_ID
        AND CARD_ID = VAR_CARD_ID;

    CALL SP_DRAW_HAND(VAR_VICTIM_PLAYER_ID);

    CALL SP_SPEND_CREDITS(
            VAR_PLAYER_ID,
            (
                FN_GET_SPECIAL_COST('STEAL') +
                    FN_GET_PLAYER_HANDICAP(VAR_PLAYER_ID)
            ),
            'STEAL'
        );

    CALL SP_SPEND_CREDITS(
            VAR_VICTIM_PLAYER_ID,
            (
                FN_GET_SPECIAL_COST('STEAL-VICTIM') +
                FN_GET_PLAYER_HANDICAP_INVERSE(VAR_VICTIM_PLAYER_ID)
            ) * -1,
            'STEAL-VICTIM'
        );

    CALL SP_RESPOND_WITH_CARD(VAR_PLAYER_ID, VAR_CARD_ID, 'STEAL');
END;