DROP PROCEDURE IF EXISTS SP_RESPOND_WITH_FIND_CARD;

CREATE PROCEDURE SP_RESPOND_WITH_FIND_CARD(
    IN VAR_PLAYER_ID CHAR(36),
    IN VAR_CARD_ID CHAR(36)
)
BEGIN
    DECLARE VAR_LOBBY_ID CHAR(36) DEFAULT FN_GET_PLAYER_LOBBY_ID(VAR_PLAYER_ID);

    IF EXISTS(
        SELECT
            ID
        FROM DRAW_PILE
        WHERE LOBBY_ID = VAR_LOBBY_ID
            AND CARD_ID = VAR_CARD_ID
    ) THEN
        DELETE
        FROM DRAW_PILE
        WHERE LOBBY_ID = VAR_LOBBY_ID
            AND CARD_ID = VAR_CARD_ID;

        CALL SP_SPEND_CREDITS(
                VAR_PLAYER_ID,
                (
                    FN_GET_SPECIAL_COST('FIND') +
                        FN_GET_PLAYER_HANDICAP(VAR_PLAYER_ID)
                ),
                'FIND'
            );

        CALL SP_RESPOND_WITH_CARD(VAR_PLAYER_ID, VAR_CARD_ID, 'FIND');
    END
    IF;
END;