DROP PROCEDURE IF EXISTS SP_RESPOND_WITH_SURPRISE_CARD;

CREATE PROCEDURE SP_RESPOND_WITH_SURPRISE_CARD(IN VAR_PLAYER_ID UUID)
BEGIN
    DECLARE VAR_LOBBY_ID UUID DEFAULT FN_GET_PLAYER_LOBBY_ID(VAR_PLAYER_ID);

    DECLARE VAR_CARD_ID UUID DEFAULT FN_GET_DRAW_PILE_CARD_ID(
            'RESPONSE',
            VAR_LOBBY_ID
        );

    DELETE
    FROM DRAW_PILE
    WHERE LOBBY_ID = VAR_LOBBY_ID
        AND CARD_ID = VAR_CARD_ID;

    CALL SP_SPEND_CREDITS(
            VAR_PLAYER_ID,
            (
                FN_GET_SPECIAL_COST('SURPRISE') +
                    FN_GET_PLAYER_HANDICAP(VAR_PLAYER_ID)
            ),
            'SURPRISE'
        );

    CALL SP_RESPOND_WITH_CARD(VAR_PLAYER_ID, VAR_CARD_ID, 'SURPRISE');
END;