DROP PROCEDURE IF EXISTS SP_RESET_RESPONSES;

CREATE PROCEDURE SP_RESET_RESPONSES(IN VAR_PLAYER_ID CHAR(36))
BEGIN
    DECLARE VAR_LOBBY_ID CHAR(36) DEFAULT FN_GET_PLAYER_LOBBY_ID(VAR_PLAYER_ID);

    UPDATE PLAYER
    SET EXTRA_RESPONSES = 0
    WHERE LOBBY_ID = VAR_LOBBY_ID;

    CALL SP_SET_RESPONSES_LOBBY(VAR_LOBBY_ID);
END;