CREATE
OR REPLACE PROCEDURE SP_RESPOND_WITH_WILD_CARD(
    IN VAR_PLAYER_ID UUID,
    IN VAR_CARD_TEXT VARCHAR(255)
)
BEGIN
    DECLARE VAR_LOBBY_ID UUID DEFAULT FN_GET_PLAYER_LOBBY_ID(VAR_PLAYER_ID);
    DECLARE VAR_CARD_ID UUID DEFAULT UUID();

    INSERT INTO CARD(ID, DECK_ID, CATEGORY, TEXT)
    SELECT
        VAR_CARD_ID AS ID,
        D.ID AS DECK_ID,
        'RESPONSE' AS CATEGORY,
        VAR_CARD_TEXT AS TEXT
    FROM DECK AS D
    WHERE D.ID = VAR_LOBBY_ID
        AND D.IS_HIDDEN = TRUE;

    CALL SP_SPEND_CREDITS(
            VAR_PLAYER_ID,
            (
                FN_GET_SPECIAL_COST('WILD') +
                    FN_GET_PLAYER_HANDICAP(VAR_PLAYER_ID)
            ),
            'WILD'
        );

    CALL SP_RESPOND_WITH_CARD(VAR_PLAYER_ID, VAR_CARD_ID, 'WILD');
END;