CREATE
OR REPLACE PROCEDURE SP_RESET_RESPONSES(IN VAR_PLAYER_ID UUID)
BEGIN
    DECLARE VAR_LOBBY_ID UUID DEFAULT FN_GET_PLAYER_LOBBY_ID(VAR_PLAYER_ID);

    UPDATE CJ_PLAYER_STATE AS CJPS
        INNER JOIN PLAYER AS P ON P.ID = CJPS.PLAYER_ID
    SET CJPS.EXTRA_RESPONSES = 0
    WHERE P.LOBBY_ID = VAR_LOBBY_ID;

    CALL SP_SET_RESPONSES_LOBBY(VAR_LOBBY_ID);
END;