DROP PROCEDURE IF EXISTS SP_SET_PLAYER_INACTIVE;

CREATE PROCEDURE SP_SET_PLAYER_INACTIVE(
    IN VAR_LOBBY_ID CHAR(36),
    IN VAR_USER_ID CHAR(36)
)
BEGIN
    DECLARE VAR_PLAYER_ID CHAR(36) DEFAULT (
            SELECT
                ID
            FROM PLAYER
            WHERE LOBBY_ID = VAR_LOBBY_ID
                AND USER_ID = VAR_USER_ID
        );

    UPDATE PLAYER
    SET IS_ACTIVE = 0
    WHERE ID = VAR_PLAYER_ID;
END;