DROP PROCEDURE IF EXISTS SP_SPEND_CREDITS;

CREATE PROCEDURE SP_SPEND_CREDITS(
    IN VAR_PLAYER_ID UUID,
    IN VAR_AMOUNT INT,
    IN VAR_CATEGORY ENUM(
        'WINNING-STREAK',
        'LOSING-STREAK',
        'PURCHASE',
        'SKIP-JUDGE',
        'ALERT',
        'GAMBLE',
        'GAMBLE-WIN',
        'BET',
        'BET-WIN',
        'EXTRA-RESPONSE',
        'BLOCK-RESPONSE',
        'STEAL',
        'STEAL-VICTIM',
        'SURPRISE',
        'FIND',
        'WILD',
        'PERK'
    )
)
BEGIN
    UPDATE PLAYER
    SET CREDITS_SPENT = CREDITS_SPENT + VAR_AMOUNT
    WHERE ID = VAR_PLAYER_ID;

    INSERT INTO CREDITS_SPENT(PLAYER_ID, AMOUNT, CATEGORY)
    SELECT
        VAR_PLAYER_ID,
        VAR_AMOUNT,
        VAR_CATEGORY;

    INSERT INTO LOG_CREDITS_SPENT(LOBBY_ID, USER_ID, AMOUNT, CATEGORY)
    SELECT
        LOBBY_ID,
        USER_ID,
        VAR_AMOUNT,
        VAR_CATEGORY
    FROM PLAYER
    WHERE ID = VAR_PLAYER_ID;
END;