DROP PROCEDURE IF EXISTS SP_SKIP_JUDGE;

CREATE PROCEDURE SP_SKIP_JUDGE(IN VAR_PLAYER_ID CHAR(36))
BEGIN
    DECLARE VAR_LOBBY_ID CHAR(36) DEFAULT FN_GET_PLAYER_LOBBY_ID(VAR_PLAYER_ID);

    CALL SP_SPEND_CREDITS(
            VAR_PLAYER_ID,
            (
                FN_GET_SPECIAL_COST('SKIP-JUDGE') +
                    FN_GET_PLAYER_HANDICAP(VAR_PLAYER_ID)
            ),
            'SKIP-JUDGE'
        );

    CALL SP_SET_NEXT_JUDGE_PLAYER(VAR_LOBBY_ID);
    CALL SP_SET_RESPONSES_LOBBY(VAR_LOBBY_ID);
END;