DROP PROCEDURE IF EXISTS SP_SPEND_CREDITS_UNDO;

CREATE PROCEDURE SP_SPEND_CREDITS_UNDO(
    IN VAR_PLAYER_ID UUID,
    IN VAR_AMOUNT INT,
    IN VAR_CATEGORY ENUM(
        'WINNING-STREAK',
        'LOSING-STREAK',
        'PURCHASE',
        'SKIP-JUDGE',
        'ALERT',
        'GAMBLE',
        'GAMBLE-WIN',
        'BET',
        'BET-WIN',
        'EXTRA-RESPONSE',
        'BLOCK-RESPONSE',
        'STEAL',
        'STEAL-VICTIM',
        'SURPRISE',
        'FIND',
        'WILD',
        'PERK'
    )
)
BEGIN
    DECLARE VAR_LOBBY_ID UUID;
    DECLARE VAR_PLAYER_USER_ID UUID;

    SELECT
        LOBBY_ID,
        USER_ID
    INTO
        VAR_LOBBY_ID,
        VAR_PLAYER_USER_ID
    FROM PLAYER
    WHERE ID = VAR_PLAYER_ID;

    UPDATE PLAYER
    SET CREDITS_SPENT = CREDITS_SPENT - VAR_AMOUNT
    WHERE ID = VAR_PLAYER_ID;

    DELETE
    FROM CREDITS_SPENT
    WHERE PLAYER_ID = VAR_PLAYER_ID
        AND AMOUNT = VAR_AMOUNT
        AND CATEGORY = VAR_CATEGORY
    ORDER BY CREATED_ON_DATE DESC
    LIMIT 1;

    DELETE
    FROM LOG_CREDITS_SPENT
    WHERE LOBBY_ID = VAR_LOBBY_ID
        AND USER_ID = VAR_PLAYER_USER_ID
        AND AMOUNT = VAR_AMOUNT
        AND CATEGORY = VAR_CATEGORY
    ORDER BY CREATED_ON_DATE DESC
    LIMIT 1;
END;