CREATE
OR REPLACE PROCEDURE SP_SPEND_CREDITS(
    IN VAR_PLAYER_ID UUID,
    IN VAR_AMOUNT INT,
    IN VAR_CATEGORY ENUM(
        'WINNING-STREAK',
        'LOSING-STREAK',
        'PURCHASE',
        'SKIP-JUDGE',
        'ALERT',
        'GAMBLE',
        'GAMBLE-WIN',
        'BET',
        'BET-WIN',
        'EXTRA-RESPONSE',
        'BLOCK-RESPONSE',
        'STEAL',
        'STEAL-VICTIM',
        'SURPRISE',
        'FIND',
        'WILD',
        'PERK'
    )
) whole_proc:
BEGIN
    DECLARE VAR_LOBBY_FREE_SPECIAL_CARDS BOOLEAN DEFAULT FALSE;

    SELECT
        L.FREE_SPECIAL_CARDS
    INTO
        VAR_LOBBY_FREE_SPECIAL_CARDS
    FROM PLAYER AS P
        INNER JOIN CJ_LOBBY_SETTINGS AS L ON L.LOBBY_ID = P.LOBBY_ID
    WHERE P.ID = VAR_PLAYER_ID;

    IF VAR_LOBBY_FREE_SPECIAL_CARDS
    AND VAR_CATEGORY IN ('STEAL', 'STEAL-VICTIM', 'SURPRISE', 'FIND', 'WILD') THEN
        LEAVE whole_proc;
    END
    IF;

    UPDATE CJ_PLAYER_STATE
    SET CREDITS_SPENT = CREDITS_SPENT + VAR_AMOUNT
    WHERE PLAYER_ID = VAR_PLAYER_ID;

    INSERT INTO CREDITS_SPENT(PLAYER_ID, AMOUNT, CATEGORY)
    SELECT
        VAR_PLAYER_ID,
        VAR_AMOUNT,
        VAR_CATEGORY;

    INSERT INTO LOG_CREDITS_SPENT(LOBBY_ID, USER_ID, AMOUNT, CATEGORY)
    SELECT
        LOBBY_ID,
        USER_ID,
        VAR_AMOUNT,
        VAR_CATEGORY
    FROM PLAYER
    WHERE ID = VAR_PLAYER_ID;
END;