DROP PROCEDURE IF EXISTS SP_SET_LOSING_STREAK;

CREATE PROCEDURE SP_SET_LOSING_STREAK(IN VAR_WINNER_PLAYER_ID CHAR(36))
BEGIN
    DECLARE VAR_LOBBY_ID CHAR(36) DEFAULT FN_GET_PLAYER_LOBBY_ID(VAR_WINNER_PLAYER_ID);

    DECLARE VAR_JUDGE_PLAYER_ID CHAR(36) DEFAULT (
            SELECT
                PLAYER_ID
            FROM JUDGE
            WHERE LOBBY_ID = VAR_LOBBY_ID
        );

    DECLARE VAR_LOBBY_THRESHOLD INT DEFAULT (
            SELECT
                LOSE_STREAK_THRESHOLD
            FROM LOBBY
            WHERE ID = VAR_LOBBY_ID
        );

    DECLARE VAR_LOOP_DONE BOOLEAN DEFAULT FALSE;
    DECLARE VAR_PLAYER_ID CHAR(36);

    DECLARE VAR_PLAYER_CURSOR CURSOR
    FOR
    SELECT
        ID
    FROM PLAYER
    WHERE LOBBY_ID = VAR_LOBBY_ID
        AND IS_ACTIVE = 1
        AND LOSING_STREAK >= VAR_LOBBY_THRESHOLD;

    DECLARE CONTINUE HANDLER
    FOR NOT FOUND
    SET VAR_LOOP_DONE = TRUE;

    -- RESET LOSING STREAK OF WINNER
    UPDATE PLAYER
    SET LOSING_STREAK = 0
    WHERE ID = VAR_WINNER_PLAYER_ID;

    -- INCREMENT LOSING STREAK OF LOSERS
    UPDATE PLAYER
    SET LOSING_STREAK = LOSING_STREAK + 1
    WHERE LOBBY_ID = VAR_LOBBY_ID
        AND IS_ACTIVE = 1
        AND ID <> VAR_WINNER_PLAYER_ID
        AND ID <> VAR_JUDGE_PLAYER_ID;

    OPEN VAR_PLAYER_CURSOR;

        READ_LOOP: LOOP
        FETCH VAR_PLAYER_CURSOR
        INTO
            VAR_PLAYER_ID;

        IF VAR_LOOP_DONE THEN LEAVE READ_LOOP;
        END
        IF;

        -- AWARD CREDITS AFTER BREAKING THRESHOLD
        CALL SP_SPEND_CREDITS(
                VAR_PLAYER_ID,
                (
                    FN_GET_SPECIAL_COST('LOSING-STREAK') +
                    FN_GET_PLAYER_HANDICAP_INVERSE(VAR_PLAYER_ID)
                ) * -1,
                'LOSING-STREAK'
            );

        -- RESET STREAK AFTER BREAKING THRESHOLD
        UPDATE PLAYER
        SET LOSING_STREAK = 0
        WHERE ID = VAR_PLAYER_ID;
        END LOOP;
    CLOSE VAR_PLAYER_CURSOR;
END;