CREATE
OR REPLACE PROCEDURE SP_SET_LOSING_STREAK(IN VAR_WINNER_PLAYER_ID UUID)
BEGIN
    DECLARE VAR_LOBBY_ID UUID DEFAULT FN_GET_PLAYER_LOBBY_ID(VAR_WINNER_PLAYER_ID);

    DECLARE VAR_JUDGE_PLAYER_ID UUID DEFAULT (
            SELECT
                PLAYER_ID
            FROM JUDGE
            WHERE LOBBY_ID = VAR_LOBBY_ID
        );

    DECLARE VAR_LOBBY_THRESHOLD INT DEFAULT (
            SELECT
                LOSE_STREAK_THRESHOLD
            FROM CJ_LOBBY_SETTINGS
            WHERE LOBBY_ID = VAR_LOBBY_ID
        );

    DECLARE VAR_LOOP_DONE BOOLEAN DEFAULT FALSE;
    DECLARE VAR_PLAYER_ID UUID;

    DECLARE VAR_PLAYER_CURSOR CURSOR
    FOR
    SELECT
        P.ID
    FROM PLAYER AS P
        INNER JOIN CJ_PLAYER_STATE AS CJPS ON CJPS.PLAYER_ID = P.ID
    WHERE P.LOBBY_ID = VAR_LOBBY_ID
        AND P.IS_ACTIVE = 1
        AND CJPS.LOSING_STREAK >= VAR_LOBBY_THRESHOLD;

    DECLARE CONTINUE HANDLER
    FOR NOT FOUND
    SET VAR_LOOP_DONE = TRUE;

    -- RESET LOSING STREAK OF WINNER
    UPDATE CJ_PLAYER_STATE
    SET LOSING_STREAK = 0
    WHERE PLAYER_ID = VAR_WINNER_PLAYER_ID;

    -- INCREMENT LOSING STREAK OF LOSERS
    UPDATE CJ_PLAYER_STATE AS CJPS
        INNER JOIN PLAYER AS P ON P.ID = CJPS.PLAYER_ID
    SET CJPS.LOSING_STREAK = CJPS.LOSING_STREAK + 1
    WHERE P.LOBBY_ID = VAR_LOBBY_ID
        AND P.IS_ACTIVE = 1
        AND P.ID <> VAR_WINNER_PLAYER_ID
        AND P.ID <> VAR_JUDGE_PLAYER_ID;

    OPEN VAR_PLAYER_CURSOR;

        READ_LOOP: LOOP
        FETCH VAR_PLAYER_CURSOR
        INTO
            VAR_PLAYER_ID;

        IF VAR_LOOP_DONE THEN LEAVE READ_LOOP;
        END
        IF;

        -- AWARD CREDITS AFTER BREAKING THRESHOLD
        CALL SP_SPEND_CREDITS(
                VAR_PLAYER_ID,
                (
                    FN_GET_SPECIAL_COST('LOSING-STREAK') +
                    FN_GET_PLAYER_HANDICAP_INVERSE(VAR_PLAYER_ID)
                ) * -1,
                'LOSING-STREAK'
            );

        -- RESET STREAK AFTER BREAKING THRESHOLD
        UPDATE CJ_PLAYER_STATE
        SET LOSING_STREAK = 0
        WHERE PLAYER_ID = VAR_PLAYER_ID;
        END LOOP;
    CLOSE VAR_PLAYER_CURSOR;
END;