DROP PROCEDURE IF EXISTS SP_VOTE_TO_KICK_UNDO;

CREATE PROCEDURE SP_VOTE_TO_KICK_UNDO(
    IN VAR_VOTER_PLAYER_ID CHAR(36),
    IN VAR_SUBJECT_PLAYER_ID CHAR(36)
)
BEGIN
    DELETE
    FROM KICK
    WHERE VOTER_PLAYER_ID = VAR_VOTER_PLAYER_ID
        AND SUBJECT_PLAYER_ID = VAR_SUBJECT_PLAYER_ID;
END;