DROP PROCEDURE IF EXISTS SP_VOTE_TO_KICK;

CREATE PROCEDURE SP_VOTE_TO_KICK(
    IN VAR_VOTER_PLAYER_ID UUID,
    IN VAR_SUBJECT_PLAYER_ID UUID
)
BEGIN
    DECLARE VAR_LOBBY_ID UUID DEFAULT FN_GET_PLAYER_LOBBY_ID(VAR_SUBJECT_PLAYER_ID);

    DECLARE VAR_SUBJECT_USER_ID UUID DEFAULT (
            SELECT
                USER_ID
            FROM PLAYER
            WHERE ID = VAR_SUBJECT_PLAYER_ID
        );

    INSERT IGNORE INTO KICK(VOTER_PLAYER_ID, SUBJECT_PLAYER_ID)
    VALUES (VAR_VOTER_PLAYER_ID, VAR_SUBJECT_PLAYER_ID);

    IF(
        SELECT
            COUNT(*)
        FROM KICK
        WHERE SUBJECT_PLAYER_ID = VAR_SUBJECT_PLAYER_ID
    ) > 1 THEN
        DELETE
        FROM KICK
        WHERE SUBJECT_PLAYER_ID = VAR_SUBJECT_PLAYER_ID;

        INSERT INTO LOG_KICK(LOBBY_ID, USER_ID)
        VALUES (VAR_LOBBY_ID, VAR_SUBJECT_USER_ID);

        CALL SP_SET_PLAYER_INACTIVE(VAR_LOBBY_ID, VAR_SUBJECT_USER_ID);

        SELECT
            1;
        ELSE
        SELECT
            0;
    END
    IF;
END;