DROP PROCEDURE IF EXISTS SP_WITHDRAW_CARD;

CREATE PROCEDURE SP_WITHDRAW_CARD(IN VAR_RESPONSE_CARD_ID CHAR(36))
BEGIN
    DECLARE VAR_RESPONSE_ID CHAR(36);
    DECLARE VAR_CARD_ID CHAR(36);
    DECLARE VAR_PLAYER_ID CHAR(36);

    SELECT
        RC.RESPONSE_ID,
        RC.CARD_ID,
        R.PLAYER_ID
    INTO
        VAR_RESPONSE_ID,
        VAR_CARD_ID,
        VAR_PLAYER_ID
    FROM RESPONSE_CARD AS RC
        INNER JOIN RESPONSE AS R ON R.ID = RC.RESPONSE_ID
    WHERE RC.ID = VAR_RESPONSE_CARD_ID;

    UPDATE RESPONSE
    SET IS_REVEALED = 0,
        IS_RULEDOUT = 0
    WHERE ID = VAR_RESPONSE_ID;

    INSERT INTO HAND(PLAYER_ID, CARD_ID)
    VALUES (VAR_PLAYER_ID, VAR_CARD_ID);

    DELETE
    FROM RESPONSE_CARD
    WHERE ID = VAR_RESPONSE_CARD_ID;

    DELETE
    FROM LOG_RESPONSE_CARD
    WHERE RESPONSE_CARD_ID = VAR_RESPONSE_CARD_ID;
END;