DROP FUNCTION IF EXISTS FN_GET_SPECIAL_COST;

CREATE FUNCTION FN_GET_SPECIAL_COST(
    IN VAR_CATEGORY VARCHAR(32)
)
RETURNS INT
BEGIN
    RETURN
    CASE
        WHEN VAR_CATEGORY = 'WINNING-STREAK' THEN 1
        WHEN VAR_CATEGORY = 'LOSING-STREAK' THEN 1
        WHEN VAR_CATEGORY = 'PURCHASE' THEN 1
        WHEN VAR_CATEGORY = 'SKIP-JUDGE' THEN 5
        WHEN VAR_CATEGORY = 'EXTRA-RESPONSE' THEN 2
        WHEN VAR_CATEGORY = 'BLOCK-RESPONSE' THEN 2
        WHEN VAR_CATEGORY = 'STEAL' THEN 1
        WHEN VAR_CATEGORY = 'STEAL-VICTIM' THEN 1
        WHEN VAR_CATEGORY = 'SURPRISE' THEN 0
        WHEN VAR_CATEGORY = 'FIND' THEN 2
        WHEN VAR_CATEGORY = 'WILD' THEN 3
        WHEN VAR_CATEGORY = 'PERK' THEN 15
    END;
END;