DROP FUNCTION IF EXISTS FN_GET_PLAYER_LOBBY_ID;

CREATE FUNCTION FN_GET_PLAYER_LOBBY_ID(IN VAR_PLAYER_ID CHAR(36))
RETURNS CHAR(36)
BEGIN
    RETURN (SELECT LOBBY_ID FROM PLAYER WHERE ID = VAR_PLAYER_ID LIMIT 1);
END;