DROP FUNCTION IF EXISTS FN_USER_HAS_LOBBY_ACCESS;

CREATE FUNCTION FN_USER_HAS_LOBBY_ACCESS(
    VAR_USER_ID CHAR(36),
    VAR_LOBBY_ID CHAR(36)
)
RETURNS BOOLEAN
BEGIN
    -- USER IS ADMIN
    IF EXISTS(SELECT ID FROM USER WHERE ID = VAR_USER_ID AND IS_ADMIN = 1) THEN
        RETURN 1;
    END IF;

    -- USER HAS ACCESS
    IF EXISTS(
        SELECT
            ID
        FROM USER_ACCESS_LOBBY
        WHERE USER_ID = VAR_USER_ID
            AND LOBBY_ID = VAR_LOBBY_ID
    ) THEN
        RETURN 1;
    END IF;

    -- LOBBY IS PASSWORD PROTECTED
    RETURN (SELECT PASSWORD_HASH IS NULL FROM LOBBY WHERE ID = VAR_LOBBY_ID);
END;