CREATE PROCEDURE IF NOT EXISTS SP_DISCARD_HAND(
    IN VAR_PLAYER_ID UUID
)
BEGIN
    DECLARE VAR_LOBBY_ID UUID;
    DECLARE VAR_PLAYER_USER_ID UUID;

    SELECT LOBBY_ID,
           USER_ID
    INTO
        VAR_LOBBY_ID,
        VAR_PLAYER_USER_ID
    FROM PLAYER
    WHERE ID = VAR_PLAYER_ID;

    INSERT INTO LOG_DISCARD (LOBBY_ID, USER_ID, CARD_ID)
    SELECT VAR_LOBBY_ID       AS LOBBY_ID,
           VAR_PLAYER_USER_ID AS USER_ID,
           CARD_ID
    FROM HAND
    WHERE PLAYER_ID = VAR_PLAYER_ID
      AND IS_LOCKED = 0;

    DELETE
    FROM HAND
    WHERE PLAYER_ID = VAR_PLAYER_ID
      AND IS_LOCKED = 0;

    CALL SP_DRAW_HAND(VAR_PLAYER_ID);
END;