CREATE PROCEDURE IF NOT EXISTS SP_PICK_RANDOM_WINNER(
    IN VAR_LOBBY_ID UUID
)
BEGIN
    DECLARE VAR_RESPONSE_ID UUID;

    SELECT R.ID
    INTO VAR_RESPONSE_ID
    FROM RESPONSE AS R
             INNER JOIN PLAYER AS P ON P.ID = R.PLAYER_ID
             LEFT JOIN JUDGE AS J ON J.PLAYER_ID = P.ID
    WHERE P.LOBBY_ID = VAR_LOBBY_ID
      AND P.IS_ACTIVE = 1
      AND J.ID IS NULL
      AND R.IS_RULEDOUT = 0
    ORDER BY RAND()
    LIMIT 1;

    IF VAR_RESPONSE_ID IS NOT NULL THEN
        CALL SP_PICK_WINNER(VAR_RESPONSE_ID);
    END IF;
END;