CREATE PROCEDURE IF NOT EXISTS SP_PURCHASE_CREDITS(
    IN VAR_PLAYER_ID UUID
)
BEGIN
    DECLARE VAR_LOBBY_ID UUID;

    SELECT LOBBY_ID
    INTO VAR_LOBBY_ID
    FROM PLAYER
    WHERE ID = VAR_PLAYER_ID;

    UPDATE PLAYER
    SET CREDITS_SPENT = CREDITS_SPENT - 1
    WHERE ID <> VAR_PLAYER_ID
      AND LOBBY_ID = VAR_LOBBY_ID;

    INSERT INTO LOG_CREDITS_SPENT (LOBBY_ID, USER_ID, AMOUNT, CATEGORY)
    SELECT
        LOBBY_ID,
        USER_ID,
        -1,
        'PURCHASE'
    FROM PLAYER
    WHERE ID <> VAR_PLAYER_ID
      AND LOBBY_ID = VAR_LOBBY_ID;
END;
