CREATE PROCEDURE IF NOT EXISTS SP_START_NEW_ROUND(
    IN VAR_LOBBY_ID UUID
)
BEGIN
    UPDATE LOBBY
    SET ROUND_ID = UUID()
    WHERE ID = VAR_LOBBY_ID;

    CALL SP_SET_NEXT_JUDGE_PLAYER(VAR_LOBBY_ID);
    CALL SP_SET_NEXT_JUDGE_CARD(VAR_LOBBY_ID);

    UPDATE PLAYER
    SET BET_ON_WIN = 0,
        EXTRA_RESPONSES = 0
    WHERE LOBBY_ID = VAR_LOBBY_ID;

    -- CLEAR ALL RESPONSES
    DELETE R
    FROM RESPONSE AS R
             INNER JOIN PLAYER AS P ON P.ID = R.PLAYER_ID
    WHERE P.LOBBY_ID = VAR_LOBBY_ID;

    -- CREATE NEW RESPONSES
    CALL SP_SET_RESPONSES_LOBBY(VAR_LOBBY_ID);

    -- DELETE ANY WILD CARDS
    DELETE C
    FROM CARD AS C
             INNER JOIN DECK AS D ON D.ID = C.DECK_ID
    WHERE D.ID = VAR_LOBBY_ID
      AND D.IS_LOBBY_WILD_DECK = TRUE;
END;