CREATE PROCEDURE IF NOT EXISTS SP_SET_RESPONSES_LOBBY(
    IN VAR_LOBBY_ID UUID
)
BEGIN
    DECLARE VAR_LOOP_DONE BOOLEAN DEFAULT FALSE;
    DECLARE VAR_PLAYER_ID UUID;
    DECLARE VAR_PLAYER_CURSOR CURSOR FOR
        SELECT ID
        FROM PLAYER
        WHERE LOBBY_ID = VAR_LOBBY_ID;
    DECLARE CONTINUE HANDLER FOR NOT FOUND SET VAR_LOOP_DONE = TRUE;

    OPEN VAR_PLAYER_CURSOR;

    READ_LOOP:
    LOOP
        FETCH VAR_PLAYER_CURSOR INTO VAR_PLAYER_ID;
        IF VAR_LOOP_DONE THEN
            LEAVE READ_LOOP;
        END IF;

        CALL SP_SET_RESPONSES_PLAYER(VAR_PLAYER_ID);
    END LOOP;

    CLOSE VAR_PLAYER_CURSOR;
END;