CREATE PROCEDURE IF NOT EXISTS SP_VOTE_TO_KICK(
    IN VAR_VOTER_PLAYER_ID UUID,
    IN VAR_SUBJECT_PLAYER_ID UUID
)
BEGIN
    DECLARE VAR_LOBBY_ID UUID;
    DECLARE VAR_VOTES_RECEIVED INT;
    DECLARE VAR_SUBJECT_USER_ID UUID;

    SELECT LOBBY_ID
    INTO VAR_LOBBY_ID
    FROM PLAYER
    WHERE ID = VAR_SUBJECT_PLAYER_ID;

    INSERT IGNORE INTO KICK (VOTER_PLAYER_ID, SUBJECT_PLAYER_ID)
    VALUES (VAR_VOTER_PLAYER_ID, VAR_SUBJECT_PLAYER_ID);

    SELECT COUNT(*)
    INTO VAR_VOTES_RECEIVED
    FROM KICK
    WHERE SUBJECT_PLAYER_ID = VAR_SUBJECT_PLAYER_ID;

    IF VAR_VOTES_RECEIVED > 1 THEN
        DELETE
        FROM KICK
        WHERE SUBJECT_PLAYER_ID = VAR_SUBJECT_PLAYER_ID;

        SELECT USER_ID
        INTO VAR_SUBJECT_USER_ID
        FROM PLAYER
        WHERE ID = VAR_SUBJECT_PLAYER_ID;

        INSERT INTO LOG_KICK (LOBBY_ID, USER_ID)
        VALUES (VAR_LOBBY_ID, VAR_SUBJECT_USER_ID);

        SELECT 1;
    ELSE
        SELECT 0;
    END IF;
END;