CREATE PROCEDURE IF NOT EXISTS SP_VOTE_TO_KICK_UNDO(
    IN VAR_VOTER_PLAYER_ID UUID,
    IN VAR_SUBJECT_PLAYER_ID UUID
)
BEGIN
    DELETE
    FROM KICK
    WHERE VOTER_PLAYER_ID = VAR_VOTER_PLAYER_ID
      AND SUBJECT_PLAYER_ID = VAR_SUBJECT_PLAYER_ID;
END;