CREATE PROCEDURE IF NOT EXISTS SP_WITHDRAW_RESPONSE(
    IN VAR_RESPONSE_ID UUID
)
BEGIN
    DECLARE VAR_LOOP_DONE BOOLEAN DEFAULT FALSE;
    DECLARE VAR_RESPONSE_CARD_ID UUID;
    DECLARE VAR_RESPONSE_CARD_CURSOR CURSOR FOR
        SELECT ID
        FROM RESPONSE_CARD
        WHERE RESPONSE_ID = VAR_RESPONSE_ID;
    DECLARE CONTINUE HANDLER FOR NOT FOUND SET VAR_LOOP_DONE = TRUE;

    OPEN VAR_RESPONSE_CARD_CURSOR;

    READ_LOOP:
    LOOP
        FETCH VAR_RESPONSE_CARD_CURSOR INTO VAR_RESPONSE_CARD_ID;
        IF VAR_LOOP_DONE THEN
            LEAVE READ_LOOP;
        END IF;

        CALL SP_WITHDRAW_CARD(VAR_RESPONSE_CARD_ID);
    END LOOP;

    CLOSE VAR_RESPONSE_CARD_CURSOR;
END;