CREATE TABLE IF NOT EXISTS CARD(
    ID UUID NOT NULL DEFAULT UUID(),
    CREATED_ON_DATE DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    CHANGED_ON_DATE DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    DECK_ID UUID NULL,
    LOBBY_ID UUID NULL,
    CATEGORY ENUM('PROMPT', 'RESPONSE') NOT NULL DEFAULT 'PROMPT',
    TEXT VARCHAR(510) NOT NULL,
    YOUTUBE CHAR(11) NULL,
    IMAGE BLOB NULL,
    PRIMARY KEY(ID),
    -- A card belongs to EITHER a real deck (DECK_ID) OR, for card-judge's
    -- per-lobby wild cards, a lobby (LOBBY_ID). Wild cards are FK'd to LOBBY so
    -- they are cleaned up when the lobby is deleted; they are never listed as
    -- deck cards. Exactly-one-of is enforced by the game procedures.
    FOREIGN KEY(DECK_ID) REFERENCES DECK(ID) ON DELETE CASCADE,
    CONSTRAINT FK_CARD_LOBBY FOREIGN KEY(LOBBY_ID) REFERENCES LOBBY(ID) ON DELETE CASCADE,
    FULLTEXT KEY(TEXT),
    CONSTRAINT DECK_TEXT_UNIQUE UNIQUE(DECK_ID, TEXT)
);
