CREATE TABLE IF NOT EXISTS CARD(
    ID UUID NOT NULL DEFAULT (UUID()),
    CREATED_ON_DATE DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    CHANGED_ON_DATE DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    DECK_ID UUID NOT NULL,
    CATEGORY ENUM('PROMPT', 'RESPONSE') NOT NULL DEFAULT 'PROMPT',
    TEXT VARCHAR(510) NOT NULL,
    YOUTUBE CHAR(11) NULL,
    IMAGE BLOB NULL,
    PRIMARY KEY(ID),
    FOREIGN KEY(DECK_ID) REFERENCES DECK(ID) ON DELETE CASCADE,
    FULLTEXT KEY(TEXT),
    CONSTRAINT DECK_TEXT_UNIQUE UNIQUE(DECK_ID, TEXT)
);