CREATE TABLE IF NOT EXISTS CJ_LOBBY_SETTINGS(
    LOBBY_ID UUID NOT NULL,
    DRAW_PRIORITY ENUM('RANDOM', 'PLAYCOUNT') NOT NULL DEFAULT 'RANDOM',
    HAND_SIZE INT NOT NULL DEFAULT 8,
    ROUND_TIMER INT NOT NULL DEFAULT 0,
    FREE_CREDITS INT NOT NULL DEFAULT 3,
    FREE_SPECIAL_CARDS BOOLEAN NOT NULL DEFAULT FALSE,
    WIN_STREAK_THRESHOLD INT NOT NULL DEFAULT 3,
    LOSE_STREAK_THRESHOLD INT NOT NULL DEFAULT 3,
    ROUND_ID UUID NOT NULL DEFAULT UUID(),
    PRIMARY KEY(LOBBY_ID),
    FOREIGN KEY(LOBBY_ID) REFERENCES LOBBY(ID) ON DELETE CASCADE
);
