CREATE TABLE IF NOT EXISTS CJ_PLAYER_STATE(
    PLAYER_ID UUID NOT NULL,
    WINNING_STREAK INT NOT NULL DEFAULT 0,
    LOSING_STREAK INT NOT NULL DEFAULT 0,
    CREDITS_SPENT INT NOT NULL DEFAULT 0,
    BET_ON_WIN INT NOT NULL DEFAULT 0,
    EXTRA_RESPONSES INT NOT NULL DEFAULT 0,
    HAND_SIZE_ADVANTAGE INT NOT NULL DEFAULT 0,
    DISCARD_ADVANTAGE BOOLEAN NOT NULL DEFAULT 0,
    HANDICAP_ADVANTAGE BOOLEAN NOT NULL DEFAULT 0,
    SPY_ADVANTAGE BOOLEAN NOT NULL DEFAULT 0,
    PRIMARY KEY(PLAYER_ID),
    FOREIGN KEY(PLAYER_ID) REFERENCES PLAYER(ID) ON DELETE CASCADE
);
