CREATE TABLE IF NOT EXISTS JUDGE(
    ID CHAR(36) NOT NULL DEFAULT (UUID()),
    CREATED_ON_DATE DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    LOBBY_ID CHAR(36) NOT NULL,
    POSITION INT NOT NULL DEFAULT 1,
    PLAYER_ID CHAR(36) NULL,
    CARD_ID CHAR(36) NULL,
    BLANK_COUNT INT NOT NULL DEFAULT 1,
    RESPONSE_COUNT INT NOT NULL DEFAULT 1,
    PRIMARY KEY(ID),
    FOREIGN KEY(LOBBY_ID) REFERENCES LOBBY(ID) ON DELETE CASCADE,
    FOREIGN KEY(PLAYER_ID) REFERENCES PLAYER(ID) ON DELETE SET NULL,
    FOREIGN KEY(CARD_ID) REFERENCES CARD(ID) ON DELETE SET NULL
);