CREATE TABLE IF NOT EXISTS KICK(
    ID CHAR(36) NOT NULL DEFAULT (UUID()),
    CREATED_ON_DATE DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    VOTER_PLAYER_ID CHAR(36) NOT NULL,
    SUBJECT_PLAYER_ID CHAR(36) NOT NULL,
    PRIMARY KEY(ID),
    FOREIGN KEY(VOTER_PLAYER_ID) REFERENCES PLAYER(ID) ON DELETE CASCADE,
    FOREIGN KEY(SUBJECT_PLAYER_ID) REFERENCES PLAYER(ID) ON DELETE CASCADE,
    CONSTRAINT VOTER_SUBJECT_UNIQUE UNIQUE(VOTER_PLAYER_ID, SUBJECT_PLAYER_ID)
);