CREATE TABLE IF NOT EXISTS LOG_WIN(
    ID CHAR(36) NOT NULL DEFAULT (UUID()),
    CREATED_ON_DATE DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    RESPONSE_ID CHAR(36) NOT NULL,
    PRIMARY KEY(ID)
);