CREATE TABLE IF NOT EXISTS LOG_DISCARD(
    ID CHAR(36) NOT NULL DEFAULT (UUID()),
    CREATED_ON_DATE DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    LOBBY_ID CHAR(36) NOT NULL,
    USER_ID CHAR(36) NOT NULL,
    CARD_ID CHAR(36) NOT NULL,
    PRIMARY KEY(ID)
);