CREATE TABLE IF NOT EXISTS LOG_KICK(
    ID CHAR(36) NOT NULL DEFAULT (UUID()),
    CREATED_ON_DATE DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    LOBBY_ID CHAR(36) NOT NULL,
    USER_ID CHAR(36) NOT NULL,
    PRIMARY KEY(ID)
);