CREATE TABLE IF NOT EXISTS LOG_KICK(
    ID UUID NOT NULL DEFAULT (UUID()),
    CREATED_ON_DATE DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    LOBBY_ID UUID NOT NULL,
    USER_ID UUID NOT NULL,
    PRIMARY KEY(ID)
);