CREATE TABLE IF NOT EXISTS LOG_RESPONSE_CARD(
    ID CHAR(36) NOT NULL DEFAULT (UUID()),
    CREATED_ON_DATE DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    LOBBY_ID CHAR(36) NOT NULL,
    ROUND_ID CHAR(36) NOT NULL,
    RESPONSE_ID CHAR(36) NOT NULL,
    RESPONSE_CARD_ID CHAR(36) NOT NULL,
    JUDGE_USER_ID CHAR(36) NOT NULL,
    JUDGE_CARD_ID CHAR(36) NOT NULL,
    PLAYER_USER_ID CHAR(36) NOT NULL,
    PLAYER_CARD_ID CHAR(36) NOT NULL,
    SPECIAL_CATEGORY ENUM('SURPRISE', 'STEAL', 'FIND', 'WILD') NULL,
    PRIMARY KEY(ID)
);