CREATE TABLE IF NOT EXISTS LOG_CREDITS_SPENT(
    ID UUID NOT NULL DEFAULT (UUID()),
    CREATED_ON_DATE DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    LOBBY_ID UUID NOT NULL,
    USER_ID UUID NOT NULL,
    AMOUNT INT NOT NULL,
    CATEGORY ENUM(
        'WINNING-STREAK',
        'LOSING-STREAK',
        'PURCHASE',
        'SKIP-JUDGE',
        'ALERT',
        'GAMBLE',
        'GAMBLE-WIN',
        'BET',
        'BET-WIN',
        'EXTRA-RESPONSE',
        'BLOCK-RESPONSE',
        'STEAL',
        'STEAL-VICTIM',
        'SURPRISE',
        'FIND',
        'WILD',
        'PERK'
    ) NOT NULL,
    PRIMARY KEY(ID)
);