CREATE TABLE IF NOT EXISTS RESPONSE(
    ID CHAR(36) NOT NULL DEFAULT (UUID()),
    CREATED_ON_DATE DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    PLAYER_ID CHAR(36) NOT NULL,
    IS_REVEALED BOOLEAN NOT NULL DEFAULT 0,
    IS_RULEDOUT BOOLEAN NOT NULL DEFAULT 0,
    PRIMARY KEY(ID),
    FOREIGN KEY(PLAYER_ID) REFERENCES PLAYER(ID) ON DELETE CASCADE
);