CREATE TABLE IF NOT EXISTS USER_ACCESS_DECK(
    ID CHAR(36) NOT NULL DEFAULT (UUID()),
    CREATED_ON_DATE DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    USER_ID CHAR(36) NOT NULL,
    DECK_ID CHAR(36) NOT NULL,
    PRIMARY KEY(ID),
    FOREIGN KEY(USER_ID) REFERENCES USER (ID) ON DELETE CASCADE,
    FOREIGN KEY(DECK_ID) REFERENCES DECK(ID) ON DELETE CASCADE,
    CONSTRAINT USER_DECK_UNIQUE UNIQUE(USER_ID, DECK_ID)
);