CREATE TABLE IF NOT EXISTS WIN(
    ID UUID NOT NULL DEFAULT (UUID()),
    CREATED_ON_DATE DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    PLAYER_ID UUID NOT NULL,
    PRIMARY KEY(ID),
    FOREIGN KEY(PLAYER_ID) REFERENCES PLAYER(ID) ON DELETE CASCADE
);