CREATE TABLE IF NOT EXISTS WIN(
    ID CHAR(36) NOT NULL DEFAULT (UUID()),
    CREATED_ON_DATE DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PLAYER_ID CHAR(36) NOT NULL,
    PRIMARY KEY(ID),
    FOREIGN KEY(PLAYER_ID) REFERENCES PLAYER(ID) ON DELETE CASCADE
);