CREATE TRIGGER IF NOT EXISTS TR_PLAYER_AFTER_INSERT
    AFTER INSERT
    ON PLAYER
    FOR EACH ROW
BEGIN
    CALL SP_DRAW_HAND(NEW.ID);
    CALL SP_SET_MISSING_JUDGE_PLAYER(NEW.LOBBY_ID);
    CALL SP_SET_MISSING_JUDGE_CARD(NEW.LOBBY_ID);
    CALL SP_SET_RESPONSES_PLAYER(NEW.ID);
END;
