CREATE TABLE IF NOT EXISTS JUDGE
(
    ID              UUID     NOT NULL DEFAULT UUID(),
    CREATED_ON_DATE DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP(),

    LOBBY_ID        UUID     NOT NULL,
    POSITION        INT      NOT NULL DEFAULT 1,
    PLAYER_ID       UUID     NULL,
    CARD_ID         UUID     NULL,
    BLANK_COUNT     INT      NOT NULL DEFAULT 1,
    RESPONSE_COUNT  INT      NOT NULL DEFAULT 1,

    PRIMARY KEY (ID),
    FOREIGN KEY (LOBBY_ID) REFERENCES LOBBY (ID) ON DELETE CASCADE,
    FOREIGN KEY (PLAYER_ID) REFERENCES PLAYER (ID) ON DELETE SET NULL,
    FOREIGN KEY (CARD_ID) REFERENCES CARD (ID) ON DELETE SET NULL
);