CREATE TABLE IF NOT EXISTS KICK
(
    ID                UUID     NOT NULL DEFAULT UUID(),
    CREATED_ON_DATE   DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP(),

    VOTER_PLAYER_ID   UUID     NOT NULL,
    SUBJECT_PLAYER_ID UUID     NOT NULL,

    PRIMARY KEY (ID),
    FOREIGN KEY (VOTER_PLAYER_ID) REFERENCES PLAYER (ID) ON DELETE CASCADE,
    FOREIGN KEY (SUBJECT_PLAYER_ID) REFERENCES PLAYER (ID) ON DELETE CASCADE,
    CONSTRAINT VOTER_SUBJECT_UNIQUE UNIQUE (VOTER_PLAYER_ID, SUBJECT_PLAYER_ID)
);