CREATE TABLE IF NOT EXISTS LOBBY
(
    ID              UUID         NOT NULL DEFAULT UUID(),
    CREATED_ON_DATE DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP(),

    NAME            VARCHAR(255) NOT NULL,
    MESSAGE         VARCHAR(255) NULL,
    PASSWORD_HASH   CHAR(60)     NULL,

    HAND_SIZE             INT NOT NULL DEFAULT 8,
    CREDIT_LIMIT          INT NOT NULL DEFAULT 3,
    WIN_STREAK_THRESHOLD  INT NOT NULL DEFAULT 3,
    LOSE_STREAK_THRESHOLD INT NOT NULL DEFAULT 3,

    ROUND_ID        UUID         NOT NULL DEFAULT UUID(),

    PRIMARY KEY (ID),
    CONSTRAINT NAME_UNIQUE UNIQUE (NAME)
);