CREATE TABLE IF NOT EXISTS LOG_WILD
(
    ID              UUID         NOT NULL DEFAULT UUID(),
    CREATED_ON_DATE DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP(),

    CARD_ID         UUID         NOT NULL,
    CARD_TEXT       VARCHAR(510) NOT NULL,

    PRIMARY KEY (ID)
);