CREATE TABLE IF NOT EXISTS LOG_WIN
(
    ID              UUID     NOT NULL DEFAULT UUID(),
    CREATED_ON_DATE DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP(),

    RESPONSE_ID     UUID     NOT NULL,

    PRIMARY KEY (ID)
);