CREATE TABLE IF NOT EXISTS LOG_DRAW
(
    ID              UUID     NOT NULL DEFAULT UUID(),
    CREATED_ON_DATE DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP(),

    LOBBY_ID        UUID     NOT NULL,
    USER_ID         UUID     NOT NULL,
    CARD_ID         UUID     NOT NULL,

    PRIMARY KEY (ID)
);