CREATE TABLE IF NOT EXISTS RESPONSE
(
    ID              UUID     NOT NULL DEFAULT UUID(),
    CREATED_ON_DATE DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP(),

    PLAYER_ID       UUID     NOT NULL,
    IS_REVEALED     BOOLEAN  NOT NULL DEFAULT 0,
    IS_RULEDOUT     BOOLEAN  NOT NULL DEFAULT 0,

    PRIMARY KEY (ID),
    FOREIGN KEY (PLAYER_ID) REFERENCES PLAYER (ID) ON DELETE CASCADE
);